[package]
name = "JKD PINNACLE CONSTRUCTION"
version = "1.0.0"

[dependencies]  
php = ">=8.2"

run = "php artisan migrate --force"

[command.web]
run = "php artisan serve --host=0.0.0.0 --port=$PORT"

[command.queue]
run = "php artisan queue:work --queue=default --sleep=3 --tries=3"